# Generated by Django 6.0.4 on 2026-06-03 13:41

import Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productapplication",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=Store.models.image_upload_path,
                verbose_name="Image",
            ),
        ),
    ]
